server:
  port: 8080

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-52-204-195-41.compute-1.amazonaws.com:5432/ddgfk3evqesm17
    username: mfozipasxxtrgt
    password: ae282ec83e69637b9f519deaff87c82ed22d8deb520dfaad17a6d8e04737b861
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    initialize: true
    schema: classpath:/schema-postgresql.sql